# Generated by Django 3.1 on 2020-08-23 22:57

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Тело формы',
                'verbose_name_plural': 'Тела форм',
                'default_related_name': 'form_bodies',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Текст'), ('radio', 'Радио кнопки'), ('dropdown', 'Выпадающий список'), ('date', 'Дата'), ('checkbox', 'Чекбокс')], max_length=31)),
                ('data', models.TextField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Поле формы',
                'verbose_name_plural': 'Поля форм',
            },
        ),
        migrations.CreateModel(
            name='FormButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('form_body', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_gui.formbody', verbose_name='form_body')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forms_gui.formbutton')),
            ],
            options={
                'verbose_name': 'Кнопка с формами',
                'verbose_name_plural': 'Кнопки с формами',
            },
        ),
        migrations.AddField(
            model_name='formbody',
            name='form_fields',
            field=models.ManyToManyField(related_name='form_bodies', to='forms_gui.FormField'),
        ),
    ]
