# Generated by Django 3.1 on 2020-08-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbutton',
            name='form_body',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_button', to='forms_gui.formbody', verbose_name='form_body'),
        ),
    ]
