# Generated by Django 3.1 on 2020-08-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_gui', '0002_auto_20200820_0538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formbutton',
            options={'verbose_name': 'Кнопка с формами', 'verbose_name_plural': 'Кнопки с формами'},
        ),
        migrations.AlterField(
            model_name='formbutton',
            name='form_body',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms_gui.formbody', verbose_name='form_body'),
        ),
    ]
