# Generated by Django 3.1 on 2020-08-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_gui', '0002_auto_20200824_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formbody',
            name='form_fields',
            field=models.ManyToManyField(related_name='form_body', to='forms_gui.FormField'),
        ),
    ]
