# Generated by Django 3.1 on 2020-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_gui', '0002_usersrequest_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersrequest',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
