# Generated by Django 3.1 on 2020-08-25 18:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms_gui', '0003_auto_20200825_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formbody',
            options={'default_related_name': 'form_bodies', 'verbose_name': 'Справка', 'verbose_name_plural': 'Справки'},
        ),
        migrations.AlterModelOptions(
            name='formbutton',
            options={'verbose_name': 'Группа справки', 'verbose_name_plural': 'Группы справок'},
        ),
        migrations.AlterModelOptions(
            name='formfield',
            options={'verbose_name': 'Поле справки', 'verbose_name_plural': 'Поля справок'},
        ),
        migrations.AlterField(
            model_name='formbody',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поясняющий текст для справки'),
        ),
        migrations.AlterField(
            model_name='formbody',
            name='form_fields',
            field=models.ManyToManyField(related_name='form_body', to='forms_gui.FormField', verbose_name='Поля справки'),
        ),
        migrations.AlterField(
            model_name='formbutton',
            name='form_body',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_button', to='forms_gui.formbody', verbose_name='К какой справке ведет'),
        ),
        migrations.AlterField(
            model_name='formbutton',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forms_gui.formbutton', verbose_name='К какой группе относится'),
        ),
        migrations.AlterField(
            model_name='formbutton',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок группы'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='Тело формы'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поясняющий текст'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Обязательное ли поле'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('radio', 'Радио кнопки'), ('dropdown', 'Выпадающий список'), ('date', 'Поле даты'), ('checkbox', 'Чекбокс')], max_length=31, verbose_name='Тип поля'),
        ),
    ]
