# Generated by Django 3.1 on 2020-11-09 15:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_gui', '0003_usersrequest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/user_requests/', location='C:\\Users\\Palaguster\\Desktop\\mf_center\\user_requests'), upload_to='', verbose_name='Файл пользовательского запроса'),
        ),
    ]
