# Generated by Django 3.1 on 2020-08-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_gui', '0003_auto_20200820_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formbody',
            old_name='fields',
            new_name='form_fields',
        ),
        migrations.RemoveField(
            model_name='formbody',
            name='form_button',
        ),
    ]
