# Generated by Django 3.1 on 2020-08-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_gui', '0004_auto_20200825_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('form_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_request', to='forms_gui.formbody')),
            ],
        ),
    ]
